require("prototypes.item")
--require("prototypes.water")
require("prototypes.solar")
require("prototypes.power module")
--require("prototypes.krastorio")
--require("prototypes.warfare")
--require("prototypes.krastorio damage-technologies-bonuses-plus")
--require("prototypes.vanilla damage-technologies-bonuses-plus")
--require("prototypes.drone")